name: 'Install poetry'
description: 'Installs poetry, restore python packages and optionally export requirements.txt'

inputs:
  pypi_repo_url:
    description: 'URL of python package index (for custom packages)'
    required: true

  pypi_token_username:
    description: 'Username for authentication at python package index (for custom packages)'
    required: true

  pypi_token:
    description: 'Token for authentication at python package index (for custom packages)'
    required: true

  export_requirements:
    description: "Set to 'true' if need to generate requirements.txt"
    required: false
    default: "false"

  requirements_path:
    description: "Destination path for requirements.txt file"
    required: false
    default: ".container/requirements.txt"

outputs:
  version:
    description: "Version"
    value: ${{ steps.release-generator.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Install poetry and package dependencies
      shell: bash
      env:
        POETRY_HTTP_BASIC_AZOPS_USERNAME: ${{ inputs.pypi_token_username }}
        POETRY_HTTP_BASIC_AZOPS_PASSWORD: ${{ inputs.pypi_token }}
        EXPORT_REQUIREMENTS: ${{ inputs.export_requirements }}
        REQUIREMENTS_PATH: ${{ inputs.requirements_path }}
        REPO_URL: ${{ inputs.pypi_repo_url }}
      run: $GITHUB_ACTION_PATH/install_poetry.sh

