name: Upgrade airflow variables
description: Upgrade airflow variables

branding:
  icon: 'bar-chart'
  color: 'green'

inputs:
  project_name:
    description: Repository name
    required: true

  project_version:
    description: Repository name
    required: true

  working_directory:
    description: Working directory
    required: true

  access_token:
    description: Working directory
    required: true

  target_repo_name:
    description: Repository name
    required: false
    default: SneaksAndData/airflow-variables

  deploy_environment:
    description: Repository name
    required: false
    default: production

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/contribute_airflow_variables.sh
      working-directory: ${{ inputs.working_directory }}
      env:
        PROJECT_NAME: ${{ inputs.project_name }}
        PROJECT_VERSION: ${{ inputs.project_version }}
        DEPLOY_ENVIRONMENT: ${{ inputs.deploy_environment }}
        GH_TOKEN: ${{ inputs.access_token }}
        TARGET_REPO_NAME: ${{ inputs.target_repo_name }}
      shell: bash
