name: Deploy with github workflow
description: Deploy project using GitHub Workflow

branding:
  icon: 'bar-chart'
  color: 'green'

inputs:
  access_token:
    description: Github access token
    required: true

  repo_name:
    description: Repository name
    required: true

  workflow_name:
    description: Name of the workflow to activate
    required: true

  deploy_environment:
    description: Repository name
    required: false
    default: production

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/activate_workflow.sh
      env:
        GH_TOKEN: ${{ inputs.access_token }}
        DEPLOY_ENVIRONMENT: ${{ inputs.deploy_environment }}
        REPO_NAME: ${{ inputs.repo_name }}
        WORKFLOW_NAME: ${{ inputs.workflow_name }}
      shell: bash
