name: Upgrade airflow variables
description: Upgrade airflow variables

branding:
  icon: 'bar-chart'
  color: 'green'

inputs:
  project_name:
    description: Repository name
    required: true

  project_versoin:
    description: New project version
    required: true

  project_graph:
    description: Project graph
    required: true

  working_directory:
    description: Working directory
    required: true

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/update_variables.sh
      working-directory: ${{ inputs.working_directory }}
      env:
        PROJECT_NAME: ${{ inputs.project_name }}
        PROJECT_VERSION: ${{ inputs.project_version }}
        PROJECT_GRAPH: ${{ inputs.project_graph }}
      shell: bash
