name: Deploy python project
description: Deploys python project to azure file share

branding:
  icon: 'battery-charging'
  color: 'green'


inputs:
  cluster_sp_client_id:
    required: true
    description: Cluster service principal client ID

  cluster_sp_client_password:
    required: true
    description: Cluster service principal client password

  tenant_id:
    required: true
    description: Azure tenant id

  subscription_id:
    required: true
    description: Azure subscription id

  cluster_name:
    required: true
    description: Cluster name

  project_name:
    required: true
    description: Name of the project

  deployment_root:
    required: true
    description: Root directory for project deployments

  kubernetes_namespace:
    required: false
    default: spark
    description: Kubernetes namespace

  pvc_name:
    required: false
    default: spark-dist
    description: Kubernetes namespace

outputs:
  version:
    description: "Generated url with sas for upload"
    value: ${{ steps.get_project_version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Install azcopy
      uses: $GITHUB_ACTION_PATH/../install_azcopy
    - name: Get project version
      uses: $GITHUB_ACTION_PATH/../get_project_version
      id: version
    - name: Get cluster credentials
      uses: $GITHUB_ACTION_PATH/../login_to_aks
      with:
        cluster_sp_client_id: ${{ inputs.cluster_sp_client_id }}
        cluster_sp_client_password: ${{ inputs.cluster_sp_client_password
        tenant_id: ${{ inputs.tenant_id }}
        subscription_id: ${{ inputs.subscription_id }}
        cluster_name: ${{ inputs.cluster_name }}
    - name: Generate SAS for upload
      uses: $GITHUB_ACTION_PATH/../get_pvc_sas
      id: sas
      with:
        namespace: ${{ inputs.kubernetes_namespace }}
        claim_name: ${{ inputs.pvc_name }}
        directory_name: ${{ inputs.project_name }}/${{steps.version.outputs.version}}
    - name: Prepare site-packages for deployment
      uses: $GITHUB_ACTION_PATH/../prepare_python_deployment
      with:
        deployment_root: ${{ inputs.deployment_root }}
        project_version: ${{ steps.version.outputs.version }}
        destination: ${{ steps.sas.outputs.authorized_destination }}
        project_name: ${{ inputs.project_name }}
    - name: Deploy ${{ inputs.project_name }}
      uses: $GITHUB_ACTION_PATH/../run_azcopy
      with:
        source_directory: ${{ inputs.deployment_root }}/${{inputs.project_name}}/${{ steps.version.outputs.version }}/*
        target: ${{ steps.sas.outputs.authorized_destination }}
