name: Get Project version
description: Returns current version of the project

branding:
  icon: 'battery-charging'
  color: 'green'

outputs:
  version:
    description: "Generated url with sas for upload"
    value: ${{ steps.get_project_version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Install azcopy
      uses: $GITHUB_ACTION_PATH/../install_azcopy
    - name: Get project version
      uses: $GITHUB_ACTION_PATH/../get_project_version
      id: project_version
    - name: Get cluster credentials
      uses: $GITHUB_ACTION_PATH/../login_to_aks
      with:
        cluster_sp_client_id: ${{ steps.cluster_secrets.outputs.sparkServicePrincipalClientId }}
        cluster_sp_client_password: ${{ steps.cluster_secrets.outputs.sparkServicePrincipalPassword }}
        tenant_id: 06152121-b4c5-4544-abf5-9268e75db448
        subscription_id: 6c5538ce-b24a-4e2a-877f-979ad71287ff
        cluster_name: ${{ steps.cluster_secrets.outputs.aksName }}
    - name: Generate SAS for upload
      uses: $GITHUB_ACTION_PATH/../get_pvc_sas
      with:
        namespace: spark
        claim_name: spark-dist
        directory_name: shrek/${{steps.project_version.outputs.version}}
      id: get_sas
    - name: Deployment
      env:
        DEPLOYMENT_ROOT: ${{ secrets.DEPLOYMENT_ROOT }}
        PROJECT_VERSION: ${{ steps.project_version.outputs.version }}
        DESTINATION: ${{ steps.get_sas.outputs.authorized_destination }}
      shell: bash
      run: |
        echo "Preparing upload for SHREK $PROJECT_VERSION"
        
        echo "Deploying SHREK $PROJECT_VERSION"
        ./azcopy copy ./"$DEPLOYMENT_ROOT/shrek/$PROJECT_VERSION/*" $DESTINATION --recursive --overwrite true --put-md5       
