name: Deploy python code
description: Deploy source code of python application

branding:
  icon: 'battery-charging'
  color: 'green'

inputs:
  output_directory:
    description: Output directory
    required: true

  project_version:
    description: Version of project to deploy
    required: true

  project_name:
    description: Name of project to deploy
    required: true

  destination:
    required: true
    description: Destination directory or SAS token

  project_directory:
    description: Name of directory within the project to deploy
    required: false

  python_version:
    description: Python version
    required: false
    default: "3.9"

runs:
  using: "composite"
  steps:
    - name: Prepare python deployment
      shell: bash
      run: $GITHUB_ACTION_PATH/deploy_poetry_project_to_azfs.sh
      env:
        OUTPUT_DIRECTORY: ${{ inputs.output_directory }}
        PROJECT_VERSION: ${{ inputs.project_version }}
        PROJECT_NAME: ${{ inputs.project_name }}
        PROJECT_DIRECTORY : ${{ inputs.project_directory }}
        PYTHON_VERSION: ${{ inputs.python_version }}
        DESTINATION: ${{ inputs.destination }}
