name: Deploy python code
description: Deploy source code of python application

branding:
  icon: 'battery-charging'
  color: 'green'

inputs:
  project_version:
    description: Version of project to deploy
    required: true

  project_name:
    description: Name of project to deploy
    required: true

  destination:
    required: true
    description: Destination directory or SAS token

  project_directory:
    description: Name of directory within the project to deploy
    required: false

  target_project_subdirectory:
    description: Name of target directory inside site packages
    required: false

  python_version:
    description: Python version
    required: false
    default: "3.9"

  deployment_root:
    required: true
    description: Root directory in the deployment file structure

runs:
  using: "composite"
  steps:
    - name: Prepare python deployment
      shell: bash
      run: $GITHUB_ACTION_PATH/deploy_poetry_project_to_azfs.sh
      env:
        DEPLOYMENT_ROOT: ${{ inputs.deployment_root }}
        PROJECT_VERSION: ${{ inputs.project_version }}
        PROJECT_NAME: ${{ inputs.project_name }}
        PROJECT_DIRECTORY : ${{ inputs.project_directory }}
        TARGET_PROJECT_SUBDIRECTORY : ${{ inputs.target_project_subdirectory }}
        PYTHON_VERSION: ${{ inputs.python_version }}
        DESTINATION: ${{ inputs.destination }}
