name: Prepare python deployment
description: Prepare source deployment of python application

branding:
  icon: 'battery-charging'
  color: 'green'

inputs:
  output_directory:
    description: Output directory
    required: true

  project_version:
    description: Version of project to deploy
    required: true

  project_name:
    description: Name of project to deploy
    required: true

runs:
  using: "composite"
  steps:
    - name: Prepare python deployment
      shell: bash
      run: $GITHUB_ACTION_PATH/prepare_python_deployment.sh
      env:
        OUTPUT_DIRECTORY: ${{ inputs.output_directory }}
        PROJECT_VERSION: ${{ inputs.project_version }}
        PROJECT_NAME: ${{ inputs.project_name }}
