name: Run azcopy
description: Copy files with azcopy

branding:
  icon: 'battery-charging'
  color: 'green'

inputs:

  deploy_environment:
    required: true
    description: Deploy environment either 'test' or 'production'

  project_name:
    description: Name of project to deploy
    required: true

  ssh_key:
    description: SSH key fot spark cluster
    required: true

  spark_host:
    description: Spark server host
    required: true

  spark_port:
    description: Spark server port
    required: true

  spark_user:
    description: Spark server user
    required: true

runs:
  using: "composite"
  steps:
    - name: Prepare python deployment
      shell: bash
      run: $GITHUB_ACTION_PATH/run_dbt_compile.sh
      env:
        DEPLOY_ENVIRONMENT: ${{ inputs.environment }}
        PROJECT_NAME: ${{ inputs.project_name }}
        SSH_KEY: ${{ inputs.ssh_key }}
        SPARK_USER: ${{ inputs.spark_user }}
        SPARK_HOST: ${{ inputs.spark_host }}
        SPARK_PORT: ${{ inputs.spark_port }}
