name: Read airflow variable
description: Read airflow variable from directory

branding:
  icon: 'bar-chart'
  color: 'green'

inputs:
  project_name:
    description: Project name
    required: true

  root_directory:
    description: Root directory with variables repository
    required: false
    default: 'airflow-variables'

  variables_sub_path:
    description: Subdirectory with JSON-encoded file with variable
    required: false
    default: .helm/variables/

outputs:
  airflow_variable:
    description: JSON-encoded airflow variable
    value: ${{ steps.read_variable.outputs.airflow_variable }}

runs:
  using: "composite"
  steps:
    - run: cat "$VARIABLES_SUB_PATH/${PROJECT_NAME//-/_}.json" >> "$GITHUB_OUTPUT"
      # $GITHUB_ACTION_PATH/read_airflow_variable.sh
      working-directory: ${{ inputs.root_directory }}
      env:
        PROJECT_NAME: ${{ inputs.project_name }}
        VARIABLES_SUB_PATH: ${{ inputs.variables_sub_path}}
      id: read_variable
      shell: bash
