name: Contribute Changes
description: Contributes any changes made on a checked out repository.

branding:
  icon: 'bar-chart'
  color: 'green'

inputs:
  project_name:
    description: Name of name of the project (file with airflow variables)
    required: true

  project_version:
    description: New version of project to set
    required: true

  working_directory:
    description: Directory with airflow-variables repository
    required: true

  access_token:
    description: Github access token
    required: true

  merge:
    description: Set true if need to immediately merge changes
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/contribute_changes.sh
      working-directory: ${{ inputs.working_directory }}
      env:
        PROJECT_NAME: ${{ inputs.project_name }}
        PROJECT_VERSION: ${{ inputs.project_version }}
        GH_TOKEN: ${{ inputs.access_token }}
        MERGE: ${{ inputs.merge }}
      shell: bash
