name: 'Semver Release'
description: 'Creates a tag in git repo with new semver release'

branding:
  icon: 'tag'
  color: 'green'

inputs:
  major_v:
    description: major version of current release
    required: true

  minor_v:
    description: minor version of current release
    required: true

  assets_path:
    description: optional release assets. All files under the path prefix will be uploaded as release assets.
    required: false

outputs:
  version:
    description: "Version"
    value: ${{ steps.release-generator.outputs.version }}

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/semver_release.sh
      id: release-generator
      env:
        MAJOR_V: ${{ inputs.major_v }}
        MINOR_V: ${{ inputs.minor_v }}
        GITHUB_TOKEN: ${{ github.token }}
        TARGET_BRANCH_MAME: ${{ github.ref }}
        ASSETS_LOCATION: ${{ github.assets_path }}
      shell: bash
