name: Run shellcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate_commit:
    name: Validate code by shellcheck
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v2
      - uses: bewuethr/shellcheck-action@v2.1.0
      - uses: ./install_poetry/
        name: Check install_poetry action
        with:
          pypi_repo_url: "${{ secrets.AZOPS_PYPI_REPO_URL }}"
          pypi_token_username: "${{ secrets.AZOPS_PAT_USER }}"
          pypi_token: "${{ secrets.AZOPS_PAT }}"
