name: Release a new version

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create Release
        id: create-release
        uses: ./semver_release/
        with:
          major_v: 0
          minor_v: 0
      - name: Print version
        run:  "echo \"New version is: ${{ steps.create-release.outputs.version }}\""
        shell: bash

