name: Release a new version

on:
  workflow_dispatch:
  pull_request:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create Release
        uses: ./semver_release/
        with:
          major_v: 0
          minor_v: 0
